volumes:
  javastream_data:

services:
  javastream:
    container_name: javastream
    image: javastream
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - javastream_data:/data
